## **Load Dataset**

In [23]:
import pandas as pd
import numpy as np
import torch
from torch.autograd import Variable

#### **Using Pandas**

In [24]:
_x_train = pd.read_csv(r"C:\Users\91939\Downloads\datasets\csv-fashion-mnist\train_LbELtWX\train.csv").astype(np.float32)
_y_train = pd.read_csv(r"C:\Users\91939\Downloads\datasets\csv-fashion-mnist\test_ScVgIM0\test.csv").astype(np.float32)

In [25]:
_x_train

id  label
0          1.0    9.0
1          2.0    0.0
2          3.0    0.0
3          4.0    3.0
4          5.0    0.0
...        ...    ...
59995  59996.0    5.0
59996  59997.0    1.0
59997  59998.0    3.0
59998  59999.0    0.0
59999  60000.0    5.0

[60000 rows x 2 columns]

In [26]:
_y_train.head()

id
0  60001.0
1  60002.0
2  60003.0
3  60004.0
4  60005.0

In [27]:
_x_train = torch.tensor(_x_train.values)
_y_train = torch.tensor(_y_train.values)

In [28]:
print(_x_train)

tensor([[1.0000e+00, 9.0000e+00],
        [2.0000e+00, 0.0000e+00],
        [3.0000e+00, 0.0000e+00],
        ...,
        [5.9998e+04, 3.0000e+00],
        [5.9999e+04, 0.0000e+00],
        [6.0000e+04, 5.0000e+00]])


In [29]:
print(_y_train)

tensor([[60001.],
        [60002.],
        [60003.],
        ...,
        [69998.],
        [69999.],
        [70000.]])


#### **Using np.array()**

In [30]:
_x_train = np.array([[3.3], [4.4], [5.5], [6.71], [6.93], [4.168], [9.779], [6.182], [7.59], [2.167], [7.042], [10.791], [5.313], [7.997], [3.1]], dtype=np.float32)
_y_train = np.array([[1.7], [2.76], [2.09], [3.19], [1.694], [1.573], [3.366], [2.596], [2.53], [1.221], [2.827], [3.465], [1.65], [2.904], [1.3]], dtype=np.float32)

In [31]:
print(_x_train)

[[ 3.3  ]
 [ 4.4  ]
 [ 5.5  ]
 [ 6.71 ]
 [ 6.93 ]
 [ 4.168]
 [ 9.779]
 [ 6.182]
 [ 7.59 ]
 [ 2.167]
 [ 7.042]
 [10.791]
 [ 5.313]
 [ 7.997]
 [ 3.1  ]]


In [32]:
print(_y_train)

[[1.7  ]
 [2.76 ]
 [2.09 ]
 [3.19 ]
 [1.694]
 [1.573]
 [3.366]
 [2.596]
 [2.53 ]
 [1.221]
 [2.827]
 [3.465]
 [1.65 ]
 [2.904]
 [1.3  ]]


In [33]:
_x_train = torch.from_numpy(_x_train)
_y_train = torch.from_numpy(_y_train)

In [34]:
print(_x_train)

tensor([[ 3.3000],
        [ 4.4000],
        [ 5.5000],
        [ 6.7100],
        [ 6.9300],
        [ 4.1680],
        [ 9.7790],
        [ 6.1820],
        [ 7.5900],
        [ 2.1670],
        [ 7.0420],
        [10.7910],
        [ 5.3130],
        [ 7.9970],
        [ 3.1000]])


In [35]:
print(_y_train)

tensor([[1.7000],
        [2.7600],
        [2.0900],
        [3.1900],
        [1.6940],
        [1.5730],
        [3.3660],
        [2.5960],
        [2.5300],
        [1.2210],
        [2.8270],
        [3.4650],
        [1.6500],
        [2.9040],
        [1.3000]])


#### **Using asarray()**

In [36]:
_x_train = np.asarray([float(x) + 1.5 for x in range(10)])
_y_train = np.asarray([float(y) + 0.25 for y in range(5)])

In [37]:
print(_x_train)

[ 1.5  2.5  3.5  4.5  5.5  6.5  7.5  8.5  9.5 10.5]


In [38]:
print(_y_train)

[0.25 1.25 2.25 3.25 4.25]


In [39]:
dtype = torch.FloatTensor
_x_train = Variable(torch.from_numpy(_x_train).type(dtype), requires_grad=False)
_y_train = Variable(torch.from_numpy(_y_train).type(dtype), requires_grad=False)

In [40]:
print(_x_train)

tensor([ 1.5000,  2.5000,  3.5000,  4.5000,  5.5000,  6.5000,  7.5000,  8.5000,
         9.5000, 10.5000])


In [41]:
print(_y_train)

tensor([0.2500, 1.2500, 2.2500, 3.2500, 4.2500])


#### **Using ImageFolder Class**

In [56]:
from torchvision import datasets, transforms
import torch
import os

In [57]:
transform = transforms.Compose([transforms.Scale(256),
                                transforms.RandomResizedCrop(224),
                                transforms.RandomHorizontalFlip(),
                                transforms.ToTensor()
                               ])

In [58]:
folder_path = "/Users/91939/Downloads/datasets/fashion-mnist/"

In [59]:
print(os.path)

<module 'ntpath' from 'C:\\Users\\91939\\Anaconda3\\lib\\ntpath.py'>


In [60]:
print(os.path.join(folder_path))

/Users/91939/Downloads/datasets/fashion-mnist/


Keep in mind that structure of folder for using `ImageFolder` is:

class-1:
      
      * 1.jpg
      * 2.jpg

class-2: 
      
      * 3.jpg
      * 4.jpg

In [61]:
data = datasets.ImageFolder(root=os.path.join(folder_path), transform=transform)

In [62]:
print(data)

Dataset ImageFolder
    Number of datapoints: 70000
    Root location: /Users/91939/Downloads/datasets/fashion-mnist/
    StandardTransform
Transform: Compose(
               Scale(size=256, interpolation=PIL.Image.BILINEAR)
               RandomResizedCrop(size=(224, 224), scale=(0.08, 1.0), ratio=(0.75, 1.3333), interpolation=PIL.Image.BILINEAR)
               RandomHorizontalFlip(p=0.5)
               ToTensor()
           )


##### **Loading Data Using DataLoader**

In [48]:
from torch.utils.data import DataLoader

In [49]:
data_load = torch.utils.data.DataLoader(data, batch_size = 64, num_workers = 3)

#### **Creating Custom Datasets**

In [51]:
class SquareDataset(Dataset):
    def __init__(self, a=0, b=1):
        super(Dataset, self).__init__()
        assert a <= b
        self.a = a
        self.b = b
        
    def __len__(self):
         return self.b - self.a + 1
        
    def __getitem__(self, index):
        assert self.a <= index <= self.b
        return index, index**2

data_train = SquareDataset(a=1,b=64)
data_train_loader = DataLoader(data_train, batch_size=64, shuffle=True)
print(len(data_train))

NameError: name 'Dataset' is not defined

#### **Using Provided Datasets**

In [53]:
training_data = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=transforms.ToTensor()
)

test_data = datasets.FashionMNIST(
    root="data",
    train=False,
    download=True,
    transform=transforms.ToTensor()
)

0it [00:00, ?it/s]

Extracting data\FashionMNIST\raw\train-images-idx3-ubyte.gz to data\FashionMNIST\raw


0it [00:00, ?it/s]

Extracting data\FashionMNIST\raw\train-labels-idx1-ubyte.gz to data\FashionMNIST\raw


0it [00:00, ?it/s]

Extracting data\FashionMNIST\raw\t10k-images-idx3-ubyte.gz to data\FashionMNIST\raw


0it [00:00, ?it/s]

Extracting data\FashionMNIST\raw\t10k-labels-idx1-ubyte.gz to data\FashionMNIST\raw
Processing...


C:\Users\91939\Anaconda3\lib\site-packages\torchvision\datasets\mnist.py:480: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:141.)
  return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)


Done!


In [55]:
train_dataloader = DataLoader(training_data, batch_size=64, shuffle=True)
test_dataloader = DataLoader(test_data, batch_size=64, shuffle=True)