In [22]:
import cv2
import numpy as np

img = np.zeros([512, 512, 3], np.uint8)

print(img)

font = cv2.FONT_HERSHEY_SIMPLEX
img = cv2.putText(img, 'OpenCV', (4, 495), font, 4, (0, 255, 255), 10)

img = cv2.circle(img, (245, 100), 75, (0, 0, 255), -1)
img = cv2.circle(img, (245, 100), 35, (255, 255, 255), -1)

img = cv2.circle(img, (117, 308), 75, (0, 255, 0), -1)
img = cv2.circle(img, (117, 308), 35, (255, 255, 255), -1)

img = cv2.circle(img, (372, 308), 75, (255, 0, 0), -1)
img = cv2.circle(img, (372, 308), 35, (255, 255, 255), -1)

cv2.imshow('image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
